# These are supported funding model platforms

github: coderaiser
patreon: coderaiser
open_collective: cloudcmd
ko_fi: coderaiser
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#liberapay: ~1758956
